@extends('errors.layout')
@section('title', 'Page Expired')
@section('code', '419')
@section('message', 'Page Expired')
@section('description', 'Maaf, sesi Anda telah berakhir. Silakan segarkan halaman dan coba lagi.')
